version: "3.7"
services:
  database:
    image: postgres:13
    env_file: 
      - .env
    ports:
      - "5432:5432"
  reader:
    build: .
    #dockerfile: Dockerfile
    depends_on:
      - database