version: "3.8"
services:
  postgres:
    image: postgres:13
    env_file: .env
    volumes:
      - ./init:/docker-entrypoint-initdb.d/
    # container_name: gopostgres
  reader:
    image: golang:1.16
    build:
      context: .
      dockerfile: Dockerfile
    # container_name: gopower
    depends_on:
      - postgres
